[build]
  functions = "."

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[headers]]
  for = "/proxy"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Range, Authorization"
    Access-Control-Expose-Headers = "Content-Length, Content-Range, Accept-Ranges"
